services:
  - type: web
    name: imdb-sentiment-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_server:app --timeout 180 --workers 1 --threads 2 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
        value: python
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: TF_MEMORY_ALLOCATION
        value: